[output]
# Path for the generated CSV file
path = "data/search_results.csv"

[github]
per_page = 100
sort = "stars"
order = "desc"

# Maximum number of characters from README to save. Set to 0 for no limit"
max_chars=0

[query]
# Placeholder GitHub search queries
queries = [
  '"log anomaly" software',
  '"log anomaly" system',
  '"log-based anomaly" software',
  '"log-based anomaly" system',
  '"anomaly detection in log"',
]

search_in = [
  "name",
  "description",
  "readme"
]

archived = false
fork = false
stars = ">=0"
size = ">=0"
